from lynqx._src.named.constructors import (
    array as array,
    asnamedarray as asnamedarray,
)
from lynqx._src.named.creation import (
    arange as arange,
    empty as empty,
    empty_like as empty_like,
    full as full,
    full_like as full_like,
    iota as iota,
    ones as ones,
    ones_like as ones_like,
    zeros as zeros,
    zeros_like as zeros_like,
)
from lynqx._src.named.methods import register_namedarray_methods
from lynqx._src.named.operations import (
    broadcast_arrays as broadcast_arrays,
    broadcast_shapes as broadcast_shapes,
    broadcast_to as broadcast_to,
    delta as delta,
    identity as identity,
)
from lynqx._src.named.ufuncs import (
    conj as conj,
    conjugate as conjugate,
    exp as exp,
    log as log,
    log1p as log1p,
    log2 as log2,
    log10 as log10,
    logaddexp as logaddexp,
    logaddexp2 as logaddexp2,
    logical_and as logical_and,
    logical_not as logical_not,
    logical_or as logical_or,
    logical_xor as logical_xor,
    maximum as maximum,
    minimum as minimum,
    mod as mod,
    modf as modf,
    multiply as multiply,
    ndim as ndim,  # -> utils ?
    negative as negative,
    nextafter as nextafter,
    not_equal as not_equal,
    positive as positive,
    pow as pow,
    power as power,
    rad2deg as rad2deg,
    radians as radians,
    real as real,
    reciprocal as reciprocal,
    remainder as remainder,
    right_shift as right_shift,
    rint as rint,
    rsqrt as rsqrt,
    sign as sign,
    signbit as signbit,
    sin as sin,
    sinc as sinc,
    sinh as sinh,
    spacing as spacing,
    sqrt as sqrt,
    square as square,
    subtract as subtract,
    tan as tan,
    tanh as tanh,
    true_divide as true_divide,
    trunc as trunc,
)


register_namedarray_methods()
del register_namedarray_methods
