from typing import Any

import numpy as np
from jax import Array
from jax.sharding import Sharding
from jaxtyping import ScalarLike

from lynqx._src.axis import Axis
from lynqx._src.named import NamedIndexUpdateHelper

class NamedArray:
    array: Array
    axes: tuple[Axis, ...]

    @property
    def dtype(self) -> np.dtype: ...
    @property
    def nbytes(self) -> int: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def sharding(self) -> Sharding: ...
    @property
    def shape(self) -> tuple[int, ...]: ...

    # Array dunders
    def __getitem__(self, key: Any) -> NamedArray: ...
    def __setitem__(self, key, value) -> None: ...

    ## Comparisons
    def __lt__(self, other: NamedArrayLike) -> NamedArray: ...
    def __le__(self, other: NamedArrayLike) -> NamedArray: ...
    def __eq__(self, other: object, /) -> Any: ...
    def __ne__(self, other: object, /) -> Any: ...
    def __gt__(self, other: NamedArrayLike) -> NamedArray: ...
    def __ge__(self, other: NamedArrayLike) -> NamedArray: ...

    ## Unary Arithmetic
    def __neg__(self) -> NamedArray: ...
    def __pos__(self) -> NamedArray: ...
    def __abs__(self) -> NamedArray: ...
    def __invert__(self) -> NamedArray: ...

    ## Binary Arithmetic
    def __add__(self, other: NamedArrayLike) -> NamedArray: ...
    def __sub__(self, other: NamedArrayLike) -> NamedArray: ...
    def __mul__(self, other: NamedArrayLike) -> NamedArray: ...
    def __truediv__(self, other: NamedArrayLike) -> NamedArray: ...
    def __floordiv__(self, other: NamedArrayLike) -> NamedArray: ...
    def __mod__(self, other: NamedArrayLike) -> NamedArray: ...
    def __divmod__(self, other: NamedArrayLike) -> tuple[NamedArray, NamedArray]: ...
    def __pow__(self, other: NamedArrayLike) -> NamedArray: ...
    def __lshift__(self, other: NamedArrayLike) -> NamedArray: ...
    def __rshift__(self, other: NamedArrayLike) -> NamedArray: ...
    def __and__(self, other: NamedArrayLike) -> NamedArray: ...
    def __xor__(self, other: NamedArrayLike) -> NamedArray: ...
    def __or__(self, other: NamedArrayLike) -> NamedArray: ...
    def __radd__(self, other: NamedArrayLike) -> NamedArray: ...
    def __rsub__(self, other: NamedArrayLike) -> NamedArray: ...
    def __rmul__(self, other: NamedArrayLike) -> NamedArray: ...
    def __rtruediv__(self, other: NamedArrayLike) -> NamedArray: ...
    def __rfloordiv__(self, other: NamedArrayLike) -> NamedArray: ...
    def __rmod__(self, other: NamedArrayLike) -> NamedArray: ...
    def __rdivmod__(self, other: NamedArrayLike) -> tuple[NamedArray, NamedArray]: ...
    def __rpow__(self, other: NamedArrayLike) -> NamedArray: ...
    def __rlshift__(self, other: NamedArrayLike) -> NamedArray: ...
    def __rrshift__(self, other: NamedArrayLike) -> NamedArray: ...
    def __rand__(self, other: NamedArrayLike) -> NamedArray: ...
    def __rxor__(self, other: NamedArrayLike) -> NamedArray: ...
    def __ror__(self, other: NamedArrayLike) -> NamedArray: ...

    # Casting

    def __bool__(self) -> bool: ...
    def __complex__(self) -> complex: ...
    def __int__(self) -> int: ...
    def __float__(self) -> float: ...
    def __index__(self) -> int: ...
    def __array__(self, dtype: Any = None, copy: bool | None = None) -> np.ndarray: ...

    # JAX Extensions
    @property
    def at(self) -> NamedIndexUpdateHelper: ...

NamedArrayLike = NamedArray | ScalarLike
